### ISSUE TITLE
Предложить формат сообщения в лог, выбрать логгер и подключить его к проекту

### ISSUE THREAD

**Issue by yuriypVedisoft** [conelov/VedisoftInternship#2]
Делаем в 2 этапа:
1. Продумываем формат логов и обсуждаем его.
2. Обсуждаем формат логов.
3. Выбираем библиотеку логгера, которая поддерживает выбранный нами формат и уровни, перечисленные в ТЗ.
4. Обсуждаем библиотеку логгера и делаем окончательный выбор.
5. Подключаем выбранную библиотеку к проекту.

**Comment by conelov** [comment]
1st Формат логов:
%type[Debug, Info, Warning, Error];%filename:%linenumber;%time:"%msg"

**Comment by conelov** [comment]
Утверждено
%time %filename %linenumber %type[Debug, Info, Warning, Error]: "%msg"

**Comment by yuriypVedisoft** [comment]
Для логов выбрали библиотеку log4cpp. Задача выполнена.
